"""add orders and order_items tables

Revision ID: 1588ae692435
Revises: f0ed3a8373d5
Create Date: 2026-02-18 23:30:53.566336
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1588ae692435'
down_revision: Union[str, None] = 'f0ed3a8373d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'shipped', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_address_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_stripe_checkout_session_id'), 'orders', ['stripe_checkout_session_id'], unique=True)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # Postgres doesn't auto-index FK columns. order_items.order_id is the
    # primary lookup path (get all items for an order), so index it.
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_stripe_checkout_session_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
